### ISSUE TITLE
`task` status is confusing and not working properly

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#388] opened 2022-02-09 17:36 UTC
We have some race conditions aside not very clear definition in the status field that make insecure to use it to check if a task is done (despite its resources are not yet being disposed).

This is specially a bad issue for CML

**Comment by DavidGOrtega** [comment] 2022-02-09 17:37
related to #357

**Comment by 0x2b3bfa0** [comment] 2022-02-11 10:38
A task is unequivocally “done” when [`status.succeeded`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#status) is equal to the [`parallelism`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#parallelism) value. At least, when `parallelism` equals 1.

Can you add more information with regard to race conditions?

**Comment by 0x2b3bfa0** [comment] 2022-02-11 10:40
Still not sure whether this issue is going to be solved with code, documentation or both, but it's definitely worth the effort.

**Comment by 0x2b3bfa0** [comment] 2022-02-15 19:21
Off–topic: see https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#task-instances for additional statuses.

**Comment by DavidGOrtega** [comment] 2022-02-17 09:54
I like apache airflow statuses, is what we defined originally.

Look at this three examples of task being refreshed after task completion
 
```
    "status":{"running":0} -> should be "status":{"running":1} ?
    "status":{"running":0,"succeeded":2} -> succeeded 2?
```

```
    "status":{"running":1}
    "status":{"running":1,"succeeded":1}
    "status":{"running":0,"succeeded":2} -> why again 2?
```

```
    "status":{"running":1}
    "status":{"running":1,"succeeded":1}
```

I have even seen `"status":{"running":1,"succeeded":6}`

Its succeeded related to the time the task is refreshed?

**Comment by 0x2b3bfa0** [comment] 2022-02-17 23:44
> _Look at this three examples of task being refreshed after task completion_ [...] _I have even seen `"status":{"running":1,"succeeded":6}`_

That's what I wanted to know, thank you very much! 🙏🏼 If this happened with [`parallelism`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#parallelism) set to `1`, it's a bug. Can you please provide a minimal example to reproduce this condition?

> _Its succeeded related to the time the task is refreshed?_

No, it shouldn't. 🙃 

> _Running is attached to the disposal of the instance and its misleading. To me running should be reflecting the state of the task as a bash script and not tied to the hardware._

In that case, what should happen amidst two spot instances; `waiting` / `suspended`?

Currently, `running` means that there is a cloud instance running, and, implicitly, that an script has been launched on it. If the script fails or succeeds, the status will transition accordingly to `failed` or `succeeded`.

> _Also succeeded looks like if the task itself had succeeded_

Yes, it means exactly that. If the current behavior is different, it's a bug.

> _As you say and what I wanted to say is from trial 1 to 2 both tasks were finished with valid results but the output is difficult to assimilate._

Can you please elaborate on the meaning of “trial 1 to 2”?

**Comment by DavidGOrtega** [comment] 2022-02-21 17:37
> That's what I wanted to know, thank you very much! 🙏🏼 If this happened with [parallelism](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#parallelism) set to 1, it's a bug. Can you please provide a minimal example to reproduce this condition?

Sure! no parallelism being used. This is the basic example that allowed me to reach that condition.

```tf
resource "iterative_task" "tpi-examples-basic4" {
    provider = iterative

    cloud     = "az"
    region    = "us-east"
    machine   = "Standard_D2S_v3"

    workdir {
        input = "./"
    }

    script = <<-END
    #!/bin/bash
    echo 'hello tpi' > data.txt
    printenv >> data.txt
    END
}
```

**Comment by DavidGOrtega** [comment] 2022-02-21 17:40
> Yes, it means exactly that. If the current behavior is different, it's a bug.

But in the context of the script or just the internal execution of the task? If my script fails the task `succeeded` will still be true right?

**Comment by DavidGOrtega** [comment] 2022-02-21 17:50
> In that case, what should happen amidst two spot instances; waiting / suspended?

We should somehow give feedback if the task is waiting for a new provisioning. 

> the status will transition accordingly to failed or succeeded.

This is weird, specially if we use `console` its more friendly to do the check against one value

```
if [ $(terraform console <<< 'iterative_task.train.status') == 'completed' ]; then
```

I might say that the majority of the cases what I want to know is that the task is completed. Maybe then if failed the script to be able to create proper checks.
Thats why I liked the status codes.
We might define 2X for 2 being terminated and 20 or 21 being terminated and success or terminated and failed.
Status code best benefit is the capability of expansion, which is definitely good to avoid being short and changing the definition in the near future. 
A status code can always come with the description

**Comment by 0x2b3bfa0** [comment] 2022-02-21 20:22
> If my script fails the task `succeeded` will still be true right?

Wrong. If the script fails, `failed` will be incremented, but `succeeded` won't.

**Comment by 0x2b3bfa0** [comment] 2022-02-21 20:25
> I might say that the majority of the cases what I want to know is that the task is completed. Maybe then if failed the script to be able to create proper checks.
> Thats why I liked the status codes.
> We might define 2X for 2 being terminated and 20 or 21 being terminated and success or terminated and failed.
> Status code best benefit is the capability of expansion, which is definitely good to avoid being short and changing the definition in the near future.
> A status code can always come with the description

Status codes don't seem precisely user friendly. If detecting whether a task has completed (regardlessly of the `succeeded` or `failed` outcome) is so important, maybe we can add a third field with the sum of those two. 🤔

**Comment by 0x2b3bfa0** [comment] 2022-02-21 20:29
> We should somehow give feedback if the task is waiting for a new provisioning.

With methods other than `events` it would be a bit hacky, if with “provisioning” you mean “spot instance”. Still, sounds interesting.

**Comment by DavidGOrtega** [comment] 2022-03-01 12:36
> With methods other than events it would be a bit hacky, if with “provisioning” you mean “spot instance”. Still, sounds interesting.

This is a must. We need to know if the task is sleeping or running and we can already know it at least when terminating the spot instance

**Comment by DavidGOrtega** [comment] 2022-03-01 12:40
I do not find events useful right now, does not say a lot

In any case. Look at this scenario:

Task is running installing tensorflow like a boss
```
Mar 01 12:26:59 tpi000000 tpi-task[2070]: Processing triggers for man-db (2.9.1-1) ...
Mar 01 12:27:19 tpi000000 tpi-task[2070]: Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Mar 01 12:27:24 tpi000000 sudo[2069]: pam_unix(sudo:session): session closed for user root
Mar 01 12:27:25 tpi000000 tpi-task[7576]: Collecting tensorflow
Mar 01 12:27:26 tpi000000 tpi-task[7576]:   Downloading tensorflow-2.8.0-cp38-cp38-manylinux2010_x86_64.whl (497.6 MB)
```

however
```
"status": {
    "running": 0
  },
```

Not only is not reflecting the ongoing script, also says that we are not running (no spot here)

**Comment by DavidGOrtega** [comment] 2022-03-01 12:44
> tpi000000 tpi-task[2070]

what is the goal of this?
Should not be the task name or something helpful to identify the task?

**Comment by 0x2b3bfa0** [comment] 2022-03-02 22:04
> _This is a must._

Yes, but “must” be duly tracked in a separate issue.

> _We need to know if the task is sleeping or running

If I'm not mistaken, `parallelism` minus `running` is the `sleeping` value you want.

> _we can already know it at least when terminating the spot instance_

That would be useful if we kept track of terminations though a central orchestrator or a leader, able to assign machines to “threads” for `parallelism` values greater than one.

<details><summary>Random self–quote from an<a href="https://iterativeai.slack.com/archives/C6YHPP2TB/p1644522413158029?thread_ts=1644507241.091279&cid=C6YHPP2TB"> internal conversation</a>...</summary>

#### Termination notices

Spot instances can [poll](https://en.wikipedia.org/wiki/Polling_(computer_science)) a special internal URL to know if they're going to be terminated soon:
* [Amazon Web Services](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html#termination-time-metadata) — http://169.254.169.254/latest/meta-data/spot/termination-time
* [Google Cloud](https://cloud.google.com/compute/docs/instances/create-use-preemptible#detecting_if_an_instance_was_preempted) — http://metadata.google.internal/computeMetadata/v1/instance/preempted
* [Microsoft Azure](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/scheduled-events#event-scheduling) — http://169.254.169.254/metadata/scheduledevents?api-version=2020-07-01

Termination notices are available up to ~2 minutes in advance, depending on the cloud... and the weather.

#### Shutdown signal
Spot instances transition to the [G2](https://uefi.org/specs/ACPI/6.4/04_ACPI_Hardware_Specification/ACPI_Hardware_Specification.html#the-acpi-hardware-model) state before terminating, so [init](https://en.wikipedia.org/wiki/Init) has a few seconds to send a [termination signal](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGTERM) to all the processes and wait for them to finish. We use this approach to detect termination on both virtual machines (aws, az, gcp) and containers (k8s) because it's much more idiomatic than polling termination notices.

The task code has been designed to copy machine files (e.g. checkpoints) as soon as they are created or updated. Thus, it doesn't need to synchronize any data after receiving a termination notice. In the worst case scenario, the last checkpoint will be lost if there isn't enough time to transfer it.

#### Spot instance chaining
In the beginning, our code listened to those termination signals and, if the task was still running (i.e. not finished), it requested a new spot instance to resume it. This approach was rather flaky and had a fair amount of downsides.
Finally, we chose to use orchestrators to manage our instances automatically. Clouds don't charge for virtual machine orchestrators, and they do exactly what we need: launch new spot instances to resume the task up to completion.

* [Amazon Web Services](https://docs.aws.amazon.com/autoscaling/ec2/userguide/AutoScalingGroup.html) — Auto Scaling Groups
* [Microsoft Azure](https://azure.microsoft.com/es-es/services/virtual-machine-scale-sets/) — Virtual Machine Scale Sets
* [Google Cloud](https://cloud.google.com/compute/docs/instance-groups#managed_instance_groups) — Managed Instance Groups
* [Kubernetes](https://kubernetes.io/docs/concepts/workloads/controllers/job/) — Jobs

</details>

**Comment by 0x2b3bfa0** [comment] 2022-03-02 22:06
> _I do not find events useful right now, does not say a lot_

Orchestrator events come directly from the cloud API, and there isn't much we can do about that, apart from logging our own “events” from inside the cloud instances.

**Comment by 0x2b3bfa0** [comment] 2022-03-02 22:12
> <bolckquote>
> <i>Task is running installing tensorflow like a boss<br>
> <pre>
> Mar 01 12:26:59 tpi000000 tpi-task[2070]: Processing triggers for man-db (2.9.1-1) ...
> Mar 01 12:27:19 tpi000000 tpi-task[2070]: Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
> Mar 01 12:27:24 tpi000000 sudo[2069]: pam_unix(sudo:session): session closed for user root
> Mar 01 12:27:25 tpi000000 tpi-task[7576]: Collecting tensorflow
> Mar 01 12:27:26 tpi000000 tpi-task[7576]:   Downloading tensorflow-2.8.0-cp38-cp38-manylinux2010_x86_64.whl (497.6 MB)
> </pre>
>  
> however
> 
> <pre>
> "status": {
>     "running": 0
>   },
> </pre>
> 
> Not only is not reflecting the ongoing script, also says that we are not running (no spot here)
> </i></blockquote>
> 
> 

Again, that “running” value comes from the cloud API and should be accurate. Are you sure that there was a machine actually running? If so, how an I reproduce that condition?

**Comment by 0x2b3bfa0** [comment] 2022-03-02 22:25
> _`tpi000000 tpi-task[2070]`_
> _what does this mean?_
> _Should not be the task name or something helpful to identify the task?_
> _`tpi000000`_
> _maybe parallelism 0?_

This prefix is added automatically by `systemd` to all the logs, and `tpi000000` is the host name. Azure sets the host name [automatically](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-ids#scale-set-vm-computer-name) to a prefixed hexatrigesimal value.

```
Mar 01 12:26:59 tpi000000 tpi-task[2070]: Processing triggers for man-db (2.9.1-1) ...
^^^^^^ ^^^^^^^^ ^^^^^^^^^ ^^^^^^^^ ^^^^   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
date   time     host      unit     pid    message
```

---

Blatantly off-topic note: see also #378 and [`journalctl --all --output=json`](https://www.freedesktop.org/software/systemd/man/journalctl.html#-o) for evil ideas.

**Comment by casperdcl** [comment] 2022-03-02 23:47
Are we looking for something like `starting, running, succeeded, failed`?

**Comment by DavidGOrtega** [comment] 2022-03-03 14:49
```json
"status": {
    "running": 1,
    "succeeded": 1
  },
```

is going to show running forever

**Comment by casperdcl** [comment] 2022-03-03 16:52
So there are two different issues:

- what keys we have (e.g. do we need to add `starting` and `failed`?)
- the values are wrong (e.g. says `1` when it should be `0`)

**Comment by 0x2b3bfa0** [comment] 2022-03-03 17:10
> _So there are two different issues_

Yes, an issue and a feature request (?)

> _the values are wrong (e.g. says 1 when it should be 0)_

Fixing with https://github.com/iterative/terraform-provider-iterative/pull/420

> _what keys we have (e.g. do we need to add `starting` and `failed`?)_

We already have `running`, `succeeded` and `failed`. Missing would be `starting` and `paused` (waiting for spot instance), but it's more of an arithmetic issue than a technical issue.

**Comment by casperdcl** [comment] 2022-03-04 01:21
Is `queued` more appropriate than `paused`? I think it's fine to have a few keys that are mathematically related.

**Comment by 0x2b3bfa0** [comment] 2022-03-04 09:25
> _Is `queued` more appropriate than `paused`?_

`queued` would probably replace both `paused` and `starting` 👍🏼 

> _About relation to parallelism, I think it's fine to have a few keys that are mathematically related._

👍🏼 Sounds good! Then, `queued = parallelism - running`

**Comment by DavidGOrtega** [comment] 2022-03-04 09:55
> queued would probably replace both paused and starting 👍🏼

sounds good

**Closed** 2022-03-07 16:52 UTC
Labels: bug, p1-important, cloud-az

**Comment by 0x2b3bfa0** [comment] 2022-03-07 16:55
@DavidGOrtega, care to open followup issues for `running=0` from #420 and, perhaps, the “street math” `queued` status?

**Comment by 0x2b3bfa0** [comment] 2022-04-23 19:36
* https://github.com/iterative/terraform-provider-iterative/pull/521 fixed `running = 0` when the script exited with non–zero status; **not** while running; that's something I can't reproduce.

* #471 adds all the “street math” queued status logic.
